import React,{createContext,useContext,useEffect,useMemo,useRef,useState}from'react'
import {createDataSource}from'../mockSource'
export const FLAG_THRESHOLD=.3
const DataContext=createContext(null)
export function DataProvider({children}){const mode=import.meta.env.VITE_DATA_SOURCE||'mock';const [network,setNetwork]=useState({nodes:[],pipes:[]});const [levels,setLevels]=useState({});const [history,setHistory]=useState({});const [rain,setRain]=useState(0);const [minute,setMinute]=useState(0);const [detection,setDetection]=useState(null);const [selectedNode,setSelectedNode]=useState(null);const [selectedPipe,setSelectedPipe]=useState(null);const [playing,setPlaying]=useState(true);const [speed,setSpeed]=useState(1);const [threshold,setThreshold]=useState(FLAG_THRESHOLD);const source=useRef(null)
 useEffect(()=>{let alive=true;(async()=>{try{const local=await import('../mock/network.json');if(alive)setNetwork(local.default)}catch(e){console.error('Network unavailable',e)}})();return()=>{alive=false}},[])
 useEffect(()=>{const stream=createDataSource(mode,event=>{if(event.type==='tick')setMinute(Math.floor(event.time_min||0));if(event.type==='rain_update')setRain(event.intensity_mm_hr);if(event.type==='level_update'){setLevels(v=>({...v,[event.node_id]:event.level_m}));setHistory(v=>{const points=[...(v[event.node_id]||[]),{minute:source.current?.minute??0,actual:event.level_m,expected:mode==='mock'?source.current?.getExpected?.(event.node_id):undefined}];return {...v,[event.node_id]:points.slice(-120)}})}if(event.type==='detection'){setDetection(event.detection);setSelectedPipe(p=>p||event.detection.top_pipe_id)}});source.current=stream;stream.setSpeed(speed);if(playing)stream.play();return()=>stream.pause()},[mode])
 useEffect(()=>{if(!source.current)return;source.current.setSpeed(speed);playing?source.current.play():source.current.pause()},[playing,speed])
 const value=useMemo(()=>({mode,network,levels,history,rain,minute,detection,selectedNode,setSelectedNode,selectedPipe,setSelectedPipe,playing,setPlaying,speed,setSpeed,threshold,setThreshold,seek:m=>source.current?.seek(m),flagged:(detection?.candidates?.[0]?.score||0)>=threshold}),[mode,network,levels,history,rain,minute,detection,selectedNode,selectedPipe,playing,speed,threshold])
 return <DataContext.Provider value={value}>{children}</DataContext.Provider>}
export const useData=()=>useContext(DataContext)
