"""
make_swmm_inp.py

Converts a network JSON file to a SWMM .inp file.
Assumptions:
- Catchment area per node: SWMM_CATCHMENT_HA_PER_NODE (default 0.02 ha)
- Catchment imperviousness: SWMM_IMPERVIOUS_PCT (default 100%)
- Catchment width: 10 m (arbitrary)
- Catchment slope: 1% (arbitrary)
- Ponded area per node: SWMM_PONDED_AREA_M2 (default 100 m2)
- Flow units: CMS
- Flow routing: DYNWAVE
- Allow ponding: YES
- Roughness (n): 0.013 for pipes, 0.01 for impervious subcatchment

Note:
The network has 50 nodes (effective drained area ~1 ha at 0.02 ha/node).
Imperviousness is 100%, so Horton infiltration is completely bypassed/irrelevant.
The simulation bounding box covers ~25 ha (500m x 500m).
"""
import os
import json
import argparse
from math import sqrt

def build_inp_text(network: dict, storm: list, settings: dict, pipe_diam_overrides: dict = None, duration_minutes: int = 120) -> str:
    nodes = sorted(network.get("nodes", []), key=lambda n: n["id"])
    pipes = sorted(network.get("pipes", []), key=lambda p: p["id"])
    pipe_diam_overrides = pipe_diam_overrides or {}
    
    outfalls = [n for n in nodes if n.get("is_outfall")]
    junctions = [n for n in nodes if not n.get("is_outfall")]
    
    catchment_ha = settings.get("SWMM_CATCHMENT_HA_PER_NODE", 0.02)
    imperv_pct = settings.get("SWMM_IMPERVIOUS_PCT", 100)
    ponded_area = settings.get("SWMM_PONDED_AREA_M2", 100)
    
    inp = []
    
    inp.append("[TITLE]")
    inp.append("Generated by PINNpoint")
    inp.append("")
    
    inp.append("[OPTIONS]")
    inp.append("FLOW_UNITS           CMS")
    inp.append("INFILTRATION         HORTON")
    inp.append("FLOW_ROUTING         DYNWAVE")
    inp.append("START_DATE           01/01/2026")
    inp.append("START_TIME           00:00:00")
    inp.append("END_DATE             01/01/2026")
    inp.append(f"END_TIME             {duration_minutes // 60:02d}:{duration_minutes % 60:02d}:00")
    inp.append("REPORT_STEP          00:01:00")
    inp.append("WET_STEP             00:05:00")
    inp.append("DRY_STEP             01:00:00")
    inp.append("ROUTING_STEP         5")
    inp.append("ALLOW_PONDING        YES")
    inp.append("INERTIAL_DAMPING     PARTIAL")
    inp.append("VARIABLE_STEP        0.75")
    inp.append("LENGTHENING_STEP     0")
    inp.append("MIN_SURFAREA         0")
    inp.append("NORMAL_FLOW_LIMITED  BOTH")
    inp.append("SKIP_STEADY_STATE    YES")
    inp.append("FORCE_MAIN_EQUATION  H-W")
    inp.append("LINK_OFFSETS         DEPTH")
    inp.append("MIN_SLOPE            0")
    inp.append("")
    
    inp.append("[RAINGAGES]")
    inp.append(";;Name           Format    Interval SCF      Source")
    inp.append("RG1              INTENSITY 0:01     1.0      TIMESERIES TS1")
    inp.append("")
    
    inp.append("[SUBCATCHMENTS]")
    inp.append(";;Name           RainGage         Outlet           Area     %Imperv  Width    %Slope   CurbLen  SnowPack")
    for j in junctions:
        nid = j["id"]
        inp.append(f"S_{nid:<14} RG1              {nid:<16} {catchment_ha:<8} {imperv_pct:<8} 10       1        0        ")
    inp.append("")
    
    inp.append("[SUBAREAS]")
    inp.append(";;Subcatchment   N-Imperv   N-Perv     S-Imperv   S-Perv     PctZero    RouteTo    PctRouted")
    for j in junctions:
        nid = j["id"]
        inp.append(f"S_{nid:<14} 0.01       0.1        0.05       0.05       25         OUTLET    ")
    inp.append("")
    
    inp.append("[INFILTRATION]")
    inp.append(";;Subcatchment   MaxRate    MinRate    Decay      DryTime    MaxInfil")
    for j in junctions:
        nid = j["id"]
        inp.append(f"S_{nid:<14} 3.0        0.5        4          7          0")
    inp.append("")
    
    inp.append("[JUNCTIONS]")
    inp.append(";;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded")
    for j in junctions:
        nid = j["id"]
        elev = j["invert_elevation_m"]
        depth = j["depth_m"]
        inp.append(f"{nid:<16} {elev:<10} {depth:<10} 0          0          {ponded_area}")
    inp.append("")
    
    inp.append("[OUTFALLS]")
    inp.append(";;Name           Elevation  Type       Stage Data       Gated    Route To")
    for o in outfalls:
        nid = o["id"]
        elev = o["invert_elevation_m"]
        inp.append(f"{nid:<16} {elev:<10} FREE                        NO")
    inp.append("")
    
    inp.append("[CONDUITS]")
    inp.append(";;Name           FromNode         ToNode           Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow")
    for p in pipes:
        pid = p["id"]
        fn = p["from_node"]
        tn = p["to_node"]
        length = p["length_m"]
        rough = p["manning_n"]
        inp.append(f"{pid:<16} {fn:<16} {tn:<16} {length:<10} {rough:<10} 0          0          0          0")
    inp.append("")
    
    inp.append("[XSECTIONS]")
    inp.append(";;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert")
    for p in pipes:
        pid = p["id"]
        diam = pipe_diam_overrides.get(pid, p["diameter_m"])
        diam_str = f"{diam:.4f}"
        inp.append(f"{pid:<16} CIRCULAR     {diam_str:<16} 0          0          0          1          ")
    inp.append("")
    
    inp.append("[TIMESERIES]")
    inp.append(";;Name           Date       Time       Value")
    for t_min, val in storm:
        hh = int(t_min // 60)
        mm = int(t_min % 60)
        inp.append(f"TS1                         {hh:02d}:{mm:02d}      {val}")
    inp.append("")
    
    inp.append("[REPORT]")
    inp.append("INPUT      NO")
    inp.append("CONTROLS   NO")
    inp.append("SUBCATCHMENTS ALL")
    inp.append("NODES ALL")
    inp.append("LINKS ALL")
    inp.append("")
    
    inp.append("[COORDINATES]")
    inp.append(";;Node           X-Coord            Y-Coord")
    for n in nodes:
        nid = n["id"]
        x = n["lon"]
        y = n["lat"]
        inp.append(f"{nid:<16} {x:<18} {y:<18}")
    inp.append("")
    
    inp.append("[VERTICES]")
    inp.append(";;Link           X-Coord            Y-Coord")
    for p in pipes:
        pid = p["id"]
        coords = p.get("coords", [])
        if len(coords) > 2:
            # interior vertices
            for x, y in coords[1:-1]:
                inp.append(f"{pid:<16} {x:<18} {y:<18}")
    inp.append("")
    
    inp.append("[POLYGONS]")
    inp.append(";;Subcatchment   X-Coord            Y-Coord")
    for j in junctions:
        nid = j["id"]
        x = j["lon"]
        y = j["lat"]
        inp.append(f"S_{nid:<14} {x:<18} {y:<18}")
    inp.append("")
    
    return "\n".join(inp) + "\n"

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--smoke", action="store_true", help="Include smoke test storm")
    args = parser.parse_args()
    
    area = os.environ.get("AREA_NAME", "kolkata-amherst")
    data_dir = os.environ.get("DATA_DIR", "/data")
    swmm_dir = os.path.join(data_dir, "swmm")
    net_path = os.path.join(swmm_dir, f"{area}_network.json")
    out_path = os.path.join(swmm_dir, f"{area}.inp")
    
    if not os.path.exists(net_path):
        print(f"Network file not found: {net_path}")
        return
        
    with open(net_path, 'r') as f:
        network = json.load(f)
        
    settings = {
        "SWMM_CATCHMENT_HA_PER_NODE": float(os.environ.get("SWMM_CATCHMENT_HA_PER_NODE", 0.02)),
        "SWMM_IMPERVIOUS_PCT": float(os.environ.get("SWMM_IMPERVIOUS_PCT", 100.0)),
        "SWMM_PONDED_AREA_M2": float(os.environ.get("SWMM_PONDED_AREA_M2", 100.0)),
    }
    
    # 60 mm/hr for 30 min, then 0. 1 min intervals.
    storm = []
    if args.smoke or True:
        for t in range(31):
            storm.append((t, 60.0))
        storm.append((31, 0.0))
        storm.append((120, 0.0))
        
    inp_text = build_inp_text(network, storm, settings)
    
    with open(out_path, 'w') as f:
        f.write(inp_text)
        
    print(f"Generated {out_path} successfully.")

if __name__ == "__main__":
    main()
def parse_continuity_errors(rpt_text: str) -> tuple[float, float]:
    import re
    errors = re.findall(r"Continuity Error \(%\) \.+\s*([-0-9.]+)", rpt_text)
    runoff_err = float(errors[0]) if len(errors) > 0 else 0.0
    routing_err = float(errors[1]) if len(errors) > 1 else 0.0
    return runoff_err, routing_err
